# Generated by Django 4.2.16 on 2024-12-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_user_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='is_employee',
        ),
    ]
